### ISSUE TITLE
Feature request: add support for config file for cert information

### ISSUE THREAD

**Issue by Sherd21** [gregtwallace/certwarden-client#5]
When client maintain more than 2 certificates, docker config becomes very unwieldy and hard to control.
Here is an example of my compose file (and also there are ENV variables in second file as well)
<img width="602" alt="Image" src="https://github.com/user-attachments/assets/f77f4c29-6c1e-45d2-90a1-56f595d235ec" />

It would be great to have the client to support some yaml/json configuration file where we can specify all certificates we need to obtain and renew.

For example, can be something like this YML file:

```yaml
certificates:
  - domain: home.example.com
    aes_key_base64: <key>
    key_name: home.example.com-key
    key_apikey: <key>
    cert_name: home.example.com-cert
    cert_apikey: <key>
    file_update:
      start: "00:01"
      end: "23:59"
      days: "sat sun"
    restart_docker_containers:
      - container1
      - container2
  - domain: portainer.example.com
    aes_key_base64: <key>
    key_name: portainer.example.com-key
    key_apikey: <key>
    cert_name: portainer.example.com-cert
    cert_apikey: <key>
  - domain: monitoring.example.com
    aes_key_base64: <key>
    key_name: monitoring.example.com-key
    key_apikey: <key>
    cert_name: monitoring.example.com-cert
    cert_apikey: <key>
  - domain: server.example.com
    aes_key_base64: <key>
    key_name: server.example.com-key
    key_apikey: <key>
    cert_name: server.example.com-cert
    cert_apikey: <key>
```
